# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: commands
    type: object
    default: [key1=value1,key2=value2]


trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

jobs:
  - template: test-template.yml
    parameters:
      commands: ${{ parameters.commands }}
