# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java



trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

jobs:
  - template: test-template.yml
    parameters:
      steps:
        - script: echo hellp from step
        - script: echo 1
