parameters:
  - name: commands
    type: object
    default: []
  - name: isOk
    type: boolean
    default: true

jobs:
  - job: Build
    steps:
      - bash: |
          if [[ ${{parameters.isOk}} ]]
          then
            echo
          fi