parameters:
  - name: commands
    type: object
    default: []

jobs:
  - job: Build
    steps:
      - bash: |
          echo ${{join(' ', parameters.commands)}}
          echo done
          for i in "${{parameters.commands}}"
          do
            echo $i
          done